version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  app:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
    depends_on:
      - db

volumes:
  pgdata:
    driver: local